config = {
  host: "http://localhost:9200/",
  transport_options: {
    request: { timeout: 5 }
  },
}


additivity:
  index.search.slowlog: true
  index.indexing.slowlog: true

index.search.slowlog.threshold.fetch.warn: 0ms
index.search.slowlog.threshold.fetch.info: 0ms
index.search.slowlog.threshold.fetch.debug: 0ms
index.search.slowlog.threshold.fetch.trace: 0ms

if File.exists?("config/elasticsearch.yml")
  config.merge!(YAML.load_file("config/elasticsearch.yml").symbolize_keys)
end

Elasticsearch::Model.client = Elasticsearch::Client.new(config)